name: example
description: A simple command-line application.
version: 1.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  boilerplate_annotations:
  equatable:


dev_dependencies:
  boilerplate_generators:
    path: ../
  build_runner:
