targets:
  $default:
    builders:
      boilerplate_generators|props:
        generate_for:
          - test/*.dart
      boilerplate_generators|copy_with:
        generate_for:
          - test/*.dart
builders:
  props:
    import: "package:boilerplate_generators/builder.dart"
    builder_factories: ["propsGenerator"]
    build_extensions: {".dart": [".props.g.dart"]}
    auto_apply: dependents
    build_to: cache
    runs_before: ["source_gen|combining_builder"]
    applies_builders: ["source_gen|combining_builder"]
  copy_with:
    import: "package:boilerplate_generators/builder.dart"
    builder_factories: ["copyWithGenerator"]
    build_extensions: {".dart": [".copy_with.g.dart"]}
    auto_apply: dependents
    build_to: cache
    runs_before: ["source_gen|combining_builder"]
    applies_builders: ["source_gen|combining_builder"]
