name: boilerplate_generators
description: Set of code generators for copyWith and copyWithNull methods with deepCopy support, Equatable props generation.
version: 2.0.0
homepage: https://github.com/KirsApps/boilerplate_generators
topics:
  - copyWith
  - deepCopy

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  analyzer: ^5.2.0
  boilerplate_annotations: ^1.1.0
  build: ^2.3.0
  source_gen: ^1.2.2

dev_dependencies:
  build_runner: ^2.2.0
  equatable: ^2.0.5
  lint: ^1.10.0
  test: ^1.21.4
