name: build

on:
  push:
    branches: [master]

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Generate code for test
        run: dart run build_runner build test

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings lib

      - name: Run Tests
        run: dart test
